Mvc/OtoGaleri/Controllers/EkonomiController.cs
using OtoGaleri.Utils;
using OtoGaleri.ViewModels;
using OtoGaleri_BusinessLayer;
using OtoGaleri_DataAccessLayer.Entity_Framework;
using OtoGaleri_Entities.Tablolar;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace OtoGaleri.Controllers
{
    public class EkonomiController : BaseController
    {
        PersonelManager p_manager = new PersonelManager();
        HizmetlilerManager h_manager = new HizmetlilerManager();
        CalisanUcretleriManager c_manager = new CalisanUcretleriManager();
        CalisanUcretleriControlManager ck_manager = new CalisanUcretleriControlManager();
        FaturalarManager f_manager = new FaturalarManager();
        FaturaTurManager ft_manager = new FaturaTurManager();
        DigerMasraflarManager dm_manager = new DigerMasraflarManager();
        DigerMasrafTurleriManager dmt_manager = new DigerMasrafTurleriManager();
        SifirSatilanArabaManager ss_manager = new SifirSatilanArabaManager();
        KirayaVerilmisArabalarManager kv_manager = new KirayaVerilmisArabalarManager();
        IkinciElSatilmisArabalarManager is_manager = new IkinciElSatilmisArabalarManager();
         int personelaylik;

      
      
        // GET: Ekonomi
        public ActionResult Masraflar()
        {
            if (DateTime.Now.Day != 22)
            {
                int idsi = ck_manager.List().Max(x => x.Id);
                CalisanUcretleriControl ck = ck_manager.Find(x => x.Id == idsi);
                ck.OdemeYapildimi = false;
                ck_manager.Update(ck);
            }
            int personelkiralik = p_manager.List().Sum(x => x.Ucret);
            TempData["PersonelAylik"] = personelkiralik;

            int hizmetlikiralik = h_manager.List().Sum(x => x.Ucret);
            TempData["HizmetliAylik"] = hizmetlikiralik;

            int toplampara = personelkiralik + hizmetlikiralik;
            TempData["ToplamPara"] = toplampara;
            //if (c_manager.List().Count() == 0)
            //{
            //    OkViewModel notifyobj = new OkViewModel()
            //    {

            //        Title = "İçerik Olmadığı için yüklenemedi...",
            //        RedirectingUrl = "/Home/Index",

            //    };
            //    notifyobj.Items.Add("Şuana kadar çalışanların aylık zamanı gelmediği için içerik yoktur.");
            //    return View("Ok", notifyobj);
            //}
            //else
            return View(c_manager.List());
        }

    

        [HttpPost, ActionName("Masraflar")]
        public ActionResult MasraflarPostt()
        {
           
            int idsi = ck_manager.List().Max(x => x.Id);
            CalisanUcretleriControl ck = ck_manager.Find(x => x.Id == idsi);
            if (ck.OdemeYapildimi == false)
            {

                ck.OdemeYapildimi = true;
                ck_manager.Update(ck);

                foreach (var item in p_manager.List())
                {
                    CalisanUcretleri calisan = new CalisanUcretleri();
                    calisan.Adi = item.Adi;
                    calisan.Soyadi = item.Soyadi;
                    calisan.Tc = item.Tc;
                    calisan.Telefon = item.Telefon;
                    calisan.EPosta = item.Eposta;
                    calisan.Ucret = item.Ucret;
                    calisan.UcretPeriyodu = item.UcretPeriyodu;
                    c_manager.Insert(calisan);
                    personelaylik += calisan.Ucret;

                }
                foreach (var item in h_manager.List())
                {
                    CalisanUcretleri calisan = new CalisanUcretleri();
                    calisan.Adi = item.Adi;
                    calisan.Soyadi = item.Soyadi;
                    calisan.Tc = item.Tc;
                    calisan.Telefon = item.Telefon;
                    calisan.EPosta = "Gerek Yok";
                    calisan.Ucret = item.Ucret;
                    calisan.UcretPeriyodu = item.UcretPeriyodu;
                    c_manager.Insert(calisan);

                }

            }
           

            return RedirectToAction("Index","Home") ;
            
        }

      public ActionResult FaturaGor()
        {

            int digertumfatura = f_manager.List().Sum(x => x.Tutar) + f_manager.List().Sum(x => x.GecikmeTutar);
            int aylikfatura = f_manager.List(x => x.OdemeTarihi > DateTime.Now).Sum(x => x.Tutar) + f_manager.List(x => x.OdemeTarihi > DateTime.Now).Sum(x => x.GecikmeTutar);
            //bu işlemde hata olabilir 1 ay öncesini aldım     .AddMonths(-1) vardı hata veriyor onu düzelt...
            TempData["digertumfatura"] = digertumfatura;
            TempData["aylikfatura"] = aylikfatura;
            return View(f_manager.List()) ;
        }


        public ActionResult FaturaTuru()
        {


            return View();
        }
        public ActionResult FaturaTuruGor()
        {
           

            return View(ft_manager.List());
        }
        [HttpPost]
        public ActionResult FaturaTuru(FaturaTur model)
        {
            if (ModelState.IsValid)
            {
                ft_manager.Insert(model);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult FaturaEkle()
        {
            List<FaturaTur> faturalar=ft_manager.List();
            List<SelectListItem> list = new List<SelectListItem>();
            foreach(var item in faturalar)
            {
               
                 list.Add(new SelectListItem() {Text=item.FaturaAdi,Value=item.FaturaAdi });
            }
         
            ViewBag.Fatura = list;

            return View();
        }

        [HttpPost]
        public ActionResult FaturaEkle(Faturalar model)
        {
            try
            {
                f_manager.Insert(model);
                OkViewModel notifyobj = new OkViewModel()
                {

                    Title = "Fatura Ekleme",
                    RedirectingUrl = "/Ekonomi/FaturaGor",

                };
                notifyobj.Items.Add("Fatura Ekleme işleminiz başarılı bir şekilde gerçekleşmiştir.");
                return View("Ok", notifyobj);
            }
            catch (Exception)
            {
                ErrorViewModel notifyonj = new ErrorViewModel()
                {
                    Title = "Hata Oluştu.",
                };
                return View("Error", notifyonj);
            }

           
        }
        public ActionResult FaturaOde(int? id)
        {
            Faturalar f = f_manager.Find(x => x.Id == id);

            return View(f);
        }
        [HttpPost]
        public ActionResult FaturaOde(Faturalar model)
        {
            try
            {
             Faturalar f= f_manager.Find(x => x.Id == model.Id);
            f.Odendimi = true;
            f_manager.Update(f);
                OkViewModel notifyobj = new OkViewModel()
                {

                    Title = "Fatura Ödendi",
                    RedirectingUrl = "/Home/Index",

                };
                notifyobj.Items.Add("Fatura Ödeme işleminiz başarılı bir şekilde gerçekleşmiştir.");
                return View("Ok", notifyobj);
            }
            catch (Exception)
            {

                ErrorViewModel notifyonj = new ErrorViewModel()
                {
                    Title = "Hata Oluştu.",
                };
                return View("Error", notifyonj);
            }
          

        }

        public ActionResult DigerMasraflar()
        {
            int digertummasraf = dm_manager.List().Sum(x => x.Tutar);
            int aylikmasraf = dm_manager.List(x => x.OdemeTarihi > DateTime.Now).Sum(x => x.Tutar);//bu işlemde hata olabilir 1 ay öncesini aldım
            TempData["digertummasraf"] = digertummasraf;
            TempData["aylikmasraf"] = aylikmasraf;

            return View(dm_manager.List());
        }
        public ActionResult DigerMasraflarEkle()
        {

            List<DigerMasrafTurleri> faturalar = dmt_manager.List();
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var item in faturalar)
            {

                list.Add(new SelectListItem() { Text = item.MasrafAdi, Value = item.MasrafAdi });
            }

            ViewBag.Fatura = list;
            return View();
        }
        [HttpPost]
        public ActionResult DigerMasraflarEkle(DigerMasraflar model)
        {

            try
            {
                dm_manager.Insert(model);
                OkViewModel notifyobj = new OkViewModel()
                {

                    Title = "Diğer Masraf Ekleme",
                    RedirectingUrl = "/Home/Index",

                };
                notifyobj.Items.Add("Diğer Masraf Ekleme işleminiz başarılı bir şekilde gerçekleşmiştir.");
                return View("Ok", notifyobj);
            }
            catch (Exception)
            {
                ErrorViewModel notifyonj = new ErrorViewModel()
                {
                    Title = "Hata Oluştu.",
                };
                return View("Error", notifyonj);
            }

        }
        public ActionResult DigerMasraflarDetay(int? id)
        {
            DigerMasraflar d = dm_manager.Find(x => x.Id == id);
            return View(d);
        }

        [HttpPost]
        public ActionResult DigerMasraflarDetay(DigerMasraflar model)
        {
            try
            {
                DigerMasraflar f = dm_manager.Find(x => x.Id == model.Id);
                f.Odendimi = true;
                dm_manager.Update(f);
                OkViewModel notifyobj = new OkViewModel()
                {

                    Title = "Fatura Ödendi",
                    RedirectingUrl = "/Home/Index",

                };

Mvc/OtoGaleri/Views/Ekonomi/DigerMasrafTuru.cshtml
@model IEnumerable<OtoGaleri_Entities.Tablolar.DigerMasrafTurleri>
    @using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "DigerMasrafTuru";
}
<title>Diğer Masraflar Türü</title>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Diğer Masraf Türleri</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MasrafAdi)
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MasrafAdi)
                    </td>

                </tr>
            }

        </table>
        @*@Html.ActionLink("Diğer Masrafları Dön", "DigerMasraflar", "Ekonomi", null, new { @class = "btn btn-default" })
        @Html.ActionLink("Diğer Masraf Türü Ekle", "DigerMasrafTuruEkle", "Ekonomi", null, new { @class = "btn btn-primary" })*@

        <a href="@Html.EncodedLink("", "DigerMasraflar", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
            Diğer Masraflara Dön
        </a>
        <a href="@Html.EncodedLink("", "DigerMasrafTuru", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
            Diğer Masraf Türlerini Gör
        </a>

    </div>
</div>

Mvc/OtoGaleri/Views/Ekonomi/DigerMasrafTuruEkle.cshtml
@model OtoGaleri_Entities.Tablolar.DigerMasrafTurleri
    @using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "DigerMasrafTuruEkle";
}
<title>Diğer Masraflar Türü Ekle</title>
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Diğer Masraf Türü Oluştur</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm())
        {


            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.MasrafAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MasrafAdi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MasrafAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>Oluştur
                        </button>

                        @*@Html.ActionLink("Diğer Masraflara Dön", "DigerMasraflar", "Ekonomi", null, new { @class = "btn btn-default" })
                        @Html.ActionLink("Diğer Masrafların Türlerini Gör", "DigerMasrafTuru", "Ekonomi", null, new { @class = "btn btn-primary" })*@

                        <a href="@Html.EncodedLink("", "DigerMasraflar", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
                            Diğer Masraflara Dön
                        </a>
                        <a href="@Html.EncodedLink("", "DigerMasrafTuru", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
                            Diğer Masraf Türlerini Gör
                        </a>
                    </div>
                </div>
            </div>

        }



    </div>
</div>

Mvc/OtoGaleri/Views/Ekonomi/DigerMasraflarDetay.cshtml
@model OtoGaleri_Entities.Tablolar.DigerMasraflar
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "DigerMasraflarDetay";
}
<title>Diğer Masraflar Detay</title>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Diğer Ödeme Detayları</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h4>Fatura</h4>
        <hr />
        @using (Html.BeginForm())
            {
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Tutar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tutar)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.OdemeTarihi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OdemeTarihi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MasrafTuru.MasrafAdi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MasrafTuru.MasrafAdi)
                </dd>
            </dl>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>Ödemeyi Yap
                    </button>

                    @*@Html.ActionLink("Diğer Masraflara Dön", "DigerMasraflar", "Ekonomi", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Diğer Masraf Türlerini Gör", "DigerMasrafTuru", "Ekonomi", null, new { @class = "btn btn-primary" })*@

                    <a href="@Html.EncodedLink("", "DigerMasraflar", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
                        Diğer Masraflara Dön
                    </a>
                    <a href="@Html.EncodedLink("", "DigerMasrafTuru", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
                        Diğer Masraf Türlerini Gör
                    </a>
                </div>
            </div>




        }
    </div>
</div>

Mvc/OtoGaleri/Views/Ekonomi/DigerMasraflarEkle.cshtml
@model  OtoGaleri_Entities.Tablolar.DigerMasraflar
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "DigerMasraflarEkle";
}
<title>Diğer Masraflar Ekle</title>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Diğer Masrafı Oluştur</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Tutar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tutar, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tutar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.OdemeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OdemeTarihi, new { htmlAttributes = new { @class = "datapicker form-control" } })
                        @Html.ValidationMessageFor(model => model.OdemeTarihi, "", new { @class = "text-danger" })
                    </div>
                </div>
            


                <div class="form-group">
                    @Html.LabelFor(model => model.MasrafTuru.MasrafAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.MasrafTuru.MasrafAdi, (List<SelectListItem>)ViewBag.Fatura, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MasrafTuru.MasrafAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>Oluştur
                    </button>

                    @*@Html.ActionLink("Diğer Masraflara Dön", "DigerMasraflar", "Ekonomi", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Diğer Masraf Türlerini Gör", "DigerMasrafTuru", "Ekonomi", null, new { @class = "btn btn-primary" })*@

                    <a href="@Html.EncodedLink("", "DigerMasraflar", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
                        Diğer Masraflara Dön
                    </a>
                    <a href="@Html.EncodedLink("", "DigerMasrafTuru", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
                        Diğer Masraf Türlerini Gör
                    </a>
                </div>
            </div>




        }
    </div>
</div>


@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>

        $(function () {
            $(".datapicker").datepicker({

                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                //  yearRange: "2018:2020",
                minDate: new Date(2018, 0, 1),
                maxDate: new Date(2020, 0, 1),
                showOn: "both"


            });

        });
    </script>

}

Mvc/OtoGaleri/Views/Ekonomi/FaturaEkle.cshtml
@model  OtoGaleri_Entities.Tablolar.Faturalar
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "FaturaEkle";
  
   
}
<title>Fatura Ekle</title>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Fatura Oluştur</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm())
        {
            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Tutar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tutar, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tutar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GecikmeTutar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GecikmeTutar, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GecikmeTutar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.OdemeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OdemeTarihi, new { htmlAttributes = new { @class = "datapicker form-control" } })
                        @Html.ValidationMessageFor(model => model.OdemeTarihi, "", new { @class = "text-danger" })
                    </div>
                </div>
              
             
                <div class="form-group">
                    @Html.LabelFor(model => model.FaturaTuru.FaturaAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.FaturaTuru.FaturaAdi,(List<SelectListItem>)ViewBag.Fatura,new { htmlAttributes = new { @class = "form-control" } })                     
                        @Html.ValidationMessageFor(model => model.FaturaTuru.FaturaAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>Oluştur
                    </button>

                    @*@Html.ActionLink("Faturalara Dön", "FaturaGor", "Ekonomi", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Faturalara Türlerini Gör", "FaturaGor", "Ekonomi", null, new { @class = "btn btn-primary" })*@
                    <a href="@Html.EncodedLink("", "DigerMasraflar", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
                        Diğer Masraflara Dön
                    </a>
                    <a href="@Html.EncodedLink("", "DigerMasrafTuru", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
                        Diğer Masraf Türlerini Gör
                    </a>

                </div>
            </div>




        }
    </div>
</div>


@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>

        $(function () {
            $(".datapicker").datepicker({

                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                //  yearRange: "2018:2020",
                minDate: new Date(2018, 0, 1),
                maxDate: new Date(2020, 0, 1),
                showOn: "both"


            });

        });
    </script>

}

Mvc/OtoGaleri/Views/Ekonomi/FaturaOde.cshtml
@model OtoGaleri_Entities.Tablolar.Faturalar
    @using OtoGaleri.RazorHelpers
    @{
        ViewBag.Title = "FaturaOde";
    }
<title>Fatura Öde</title>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Fatura Ödeme Detayları</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h4>Fatura</h4>
            <hr />
        @using (Html.BeginForm())
            {
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Tutar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tutar)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.GecikmeTutar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.GecikmeTutar)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.OdemeTarihi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OdemeTarihi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FaturaTuru.FaturaAdi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FaturaTuru.FaturaAdi)
                </dd>
           </dl>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">

                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>Ödemeyi Yap
                </button>

                @*@Html.ActionLink("Faturalara Dön", "FaturaGor", "Ekonomi", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Faturalara Türlerini Gör", "FaturaGor", "Ekonomi", null, new { @class = "btn btn-primary" })*@
                <a href="@Html.EncodedLink("", "FaturaGor", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
                    Faturalara Dön
                </a>
                <a href="@Html.EncodedLink("", "FaturaGor", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
                    Faturalara Türlerini Gör
                </a>

            </div>
        </div>




        }
</div>
    </div>

Mvc/OtoGaleri/Views/Ekonomi/FaturaTuru.cshtml
@model OtoGaleri_Entities.Tablolar.FaturaTur
    @using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "FaturaTuru";
}


<title>Fatura Türü</title>
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Fatura Türü Oluştur</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm())
        {
        

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.FaturaAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FaturaAdi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FaturaAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                       
                            <button type="submit" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus"></span>Oluştur
                            </button>

                            @*@Html.ActionLink("Faturalara Dön", "FaturaGor", "Ekonomi", null, new { @class = "btn btn-default" })
                            @Html.ActionLink("Faturalara Türlerini Gör", "FaturaGor", "Ekonomi", null, new { @class = "btn btn-primary" })*@
                        <a href="@Html.EncodedLink("", "FaturaGor", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-default">
                            Faturalara Dön
                        </a>
                        <a href="@Html.EncodedLink("", "FaturaGor", "Ekonomi", new { }, new { @class = "form-control"})" class="btn btn-primary">
                            Faturalara Türlerini Gör
                        </a>
                        
                    </div>
                </div>
            </div>

        }



    </div>
</div>