Mvc/OtoGaleri/Controllers/HizmetlilerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OtoGaleri_Entities.Tablolar;
using OtoGaleri_BusinessLayer;
using OtoGaleri_BusinessLayer.Result;
using OtoGaleri.Utils;

namespace OtoGaleri.Controllers
{
    public class HizmetlilerController : BaseController
    {
        private HizmetlilerManager h = new HizmetlilerManager();

        // GET: Hizmetliler
        public ActionResult Index()
        {
            return View(h.List());
        }

        // GET: Hizmetliler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hizmetliler hizmetliler = h.Find(x=>x.Id==id.Value);
            if (hizmetliler == null)
            {
                return HttpNotFound();
            }
            return View(hizmetliler);
        }

        // GET: Hizmetliler/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hizmetliler hizmetliler)
        {
            Ortak123 ortakk = Session["loginy"] as Yoneticiler;
            ModelState.Remove("EkleyenPersonel");
            ModelState.Remove("EklenmeTarihi");
            if (ModelState.IsValid)
            {
                hizmetliler.EkleyenPersonel = ortakk.Adi + " " + ortakk.Soyadi;
                BusinessLayerResult<Hizmetliler> res = h.Insert(hizmetliler);
                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return View(hizmetliler);
                }
                return RedirectToAction("Index","Home");
            }

            return View(hizmetliler);
        }

        // GET: Hizmetliler/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hizmetliler hizmetliler = h.Find(x => x.Id == id.Value);
            if (hizmetliler == null)
            {
                return HttpNotFound();
            }
            return View(hizmetliler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Hizmetliler hizmetliler)
        {
            ModelState.Remove("EkleyenPersonel");
            ModelState.Remove("EklenmeTarihi");
            if (ModelState.IsValid)
            {
                BusinessLayerResult<Hizmetliler> res = h.Update(hizmetliler);
                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return View(hizmetliler);
                }
                return RedirectToAction("Index","Home");
            }
            return View(hizmetliler);
        }

        // GET: Hizmetliler/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hizmetliler hizmetliler = h.Find(x => x.Id == id.Value);
            if (hizmetliler == null)
            {
                return HttpNotFound();
            }
            return View(hizmetliler);
        }

        // POST: Hizmetliler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hizmetliler hizmetli = h.Find(x => x.Id == id);
            h.Delete(hizmetli);
            return RedirectToAction("Index","Home");
        }

      
    }
}

Mvc/OtoGaleri/Views/Hizmetliler/Create.cshtml
@model OtoGaleri_Entities.Tablolar.Hizmetliler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Create";
}
<title>Hizmetli Oluştur</title>
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Create</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Hizmetliler</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Görevi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Görevi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Görevi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tc, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Acres, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Acres, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Acres, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.EkleyenPersonel, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EkleyenPersonel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EkleyenPersonel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EklenmeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EklenmeTarihi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EklenmeTarihi, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Ucret, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ucret, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ucret, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UcretPeriyodu, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.UcretPeriyodu, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UcretPeriyodu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>Oluştur
                    </button>
                    @*@Html.ActionLink("Listeye Dön", "Index", "Hizmetliler", null, new { @class = "btn btn-default" })*@
                    <a href="@Html.EncodedLink("", "Index", "Hizmetliler", new { }, new { @class = "form-control"})" class="btn btn-default">
                        Listeye Dön
                    </a>

                </div>
            </div>
        }

        
        </div>
</div>

Mvc/OtoGaleri/Views/Hizmetliler/Delete.cshtml
@model OtoGaleri_Entities.Tablolar.Hizmetliler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Delete";
}
<title>Hizmetli Sil</title>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Silinecek</h2>
        <hr />
        <h3>Silmek İstediğine Emin Misin ?</h3>
    </div>

</div>


<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div>
            <h4>Hizmetliler</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Adi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Adi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Soyadi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Soyadi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Görevi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Görevi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tc)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Telefon)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Telefon)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Acres)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Acres)
                </dd>

             

                <dt>
                    @Html.DisplayNameFor(model => model.Ucret)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Ucret)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UcretPeriyodu)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UcretPeriyodu)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <button type="submit" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove"></span>Sil
                    </button>
                    @*@Html.ActionLink("Listeye Dön", "Index", "Hizmetliler", null, new { @class = "btn btn-default" })*@
                    <a href="@Html.EncodedLink("", "Index", "Hizmetliler", new { id=Model.Id}, new { @class = "form-control"})" class="btn btn-default">
                        Listeye Dön
                    </a>

                </div>
            }
        </div>
</div>
</div>

Mvc/OtoGaleri/Views/Hizmetliler/Details.cshtml
@model OtoGaleri_Entities.Tablolar.Hizmetliler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Details";
}
<title>Hizmetli Detay</title>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Detaylar</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <div>
            <h4>Hizmetliler</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Adi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Adi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Soyadi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Soyadi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Görevi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Görevi)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tc)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Telefon)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Telefon)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Acres)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Acres)
                </dd>

          

                <dt>
                    @Html.DisplayNameFor(model => model.Ucret)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Ucret)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UcretPeriyodu)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UcretPeriyodu)
                </dd>

            </dl>
        </div>
        <p>
            @*<a href="/Hizmetliler/Edit/@Model.Id" class="btn btn-success">
                <span class="glyphicon glyphicon-edit"></span>Düzenle
            </a>
            <a href="/Hizmetliler/Index" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span>Tüm Liste
            </a>*@
            <a href="@Html.EncodedLink("", "Edit", "Hizmetliler", new { id=Model.Id}, new { @class = "form-control"})" class="btn btn-success">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <a href="@Html.EncodedLink("", "Index", "Hizmetliler", new { id=Model.Id}, new { @class = "form-control"})" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span>Tüm Liste
            </a>
        </p>
        </div>
</div>

Mvc/OtoGaleri/Views/Hizmetliler/Edit.cshtml
@model OtoGaleri_Entities.Tablolar.Hizmetliler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Edit";
}
<title>Hizmetli Düzenle</title>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Düzenle</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Hizmetliler</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Görevi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Görevi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Görevi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tc, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Acres, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Acres, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Acres, "", new { @class = "text-danger" })
                    </div>
                </div>

               

                <div class="form-group">
                    @Html.LabelFor(model => model.Ucret, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ucret, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ucret, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UcretPeriyodu, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.UcretPeriyodu, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UcretPeriyodu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-floppy-disk"></span>Kaydet
                    </button>
                    @*@Html.ActionLink("Listeye Dön", "Index", "Hizmetliler", null, new { @class = "btn btn-default" })*@

                    <a href="@Html.EncodedLink("", "Index", "Hizmetliler", new {}, new { @class = "form-control"})" class="btn btn-default">
                        Listeye Dön
                    </a>
                </div>
            </div>
        }

        
        </div>
</div>

Mvc/OtoGaleri/Views/Hizmetliler/Index.cshtml
@model IEnumerable<OtoGaleri_Entities.Tablolar.Hizmetliler>
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Index";
}
<title>Hizmetliler</title>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Hizmetliler</h2>
        <hr />
    </div>

</div>@*sıradaki görev kayıt eklerken gereksizleri eklemeyi engellemek ardından resim eklemek*@
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <p>
            @*<a href="/Hizmetliler/Create" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>Oluştur
            </a>*@
            <a href="@Html.EncodedLink("", "Create", "Hizmetliler", new { }, new { @class = "form-control"})" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>Oluştur
            </a>
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Adi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Soyadi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Görevi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefon)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Acres)
                </th>
               
                <th>
                    @Html.DisplayNameFor(model => model.Ucret)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UcretPeriyodu)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Soyadi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Görevi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefon)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Acres)
                    </td>
                  
                    <td>
                        @Html.DisplayFor(modelItem => item.Ucret)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UcretPeriyodu)
                    </td>
                    <td>
                        @*<a href="/Hizmetliler/Edit/@item.Id" class="btn btn-warning">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <a href="/Hizmetliler/Details/@item.Id" class="btn btn-info">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>
                        <a href="/Hizmetliler/Delete/@item.Id" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>*@
                        <a href="@Html.EncodedLink("", "Edit", "Hizmetliler", new { id=item.Id}, new { @class = "form-control"})" class="btn btn-warning">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <a href="@Html.EncodedLink("", "Delete", "Hizmetliler", new { id=item.Id}, new { @class = "form-control"})" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <a href="@Html.EncodedLink("", "Details", "Hizmetliler", new { id=item.Id}, new { @class = "form-control"})" class="btn btn-info">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>
                    </td>
                </tr>
            }

        </table>
        </div>
</div>