Mvc/OtoGaleri/Controllers/YonetimController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using OtoGaleri_Entities.Tablolar;
using OtoGaleri_BusinessLayer;
using OtoGaleri_BusinessLayer.Result;
using OtoGaleri.ViewModels;
using OtoGaleri.Utils;

namespace OtoGaleri.Controllers
{
    public class YonetimController : BaseController
    {
        public ActionResult ErrorLogin()
        {
            if (Session["loginy"] == null)
            {
                ErrorViewModel notifyonj = new ErrorViewModel()
                {
                    Title = "Geçersiz İşlem.",
                    

                };
                
                return View("Error", notifyonj);
            }
            return null;
        }
       private YoneticiManager y = new YoneticiManager();
        // GET: Yonetim
        //burda kaldım araştır....
        public ActionResult Index()
        {
            ErrorLogin();
            return View(y.List());
        }

        // GET: Yonetim/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yoneticiler yoneticiler = y.Find(x=>x.Id==id.Value);
            if (yoneticiler == null)
            {
                return HttpNotFound();
            }
            return View(yoneticiler);
        }

        // GET: Yonetim/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Yonetim/Create
         [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Yoneticiler yoneticiler)
        {
            Ortak123 ortakk = Session["loginy"] as Yoneticiler;
            ModelState.Remove("KimKayitEtti");
            ModelState.Remove("KayitTarih");
            ModelState.Remove("IsActive");
            if (ModelState.IsValid)
            {
                yoneticiler.KimKayitEtti = ortakk.Adi + " " + ortakk.Soyadi;
                BusinessLayerResult<Yoneticiler> res = y.Insert(yoneticiler);
                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return View(yoneticiler);
                }
                //y.Insert(yoneticiler);
                return RedirectToAction("Index","Home");
            }

            return View(yoneticiler);
        }

        // GET: Yonetim/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yoneticiler yoneticiler = y.Find(x => x.Id == id.Value);
            if (yoneticiler == null)
            {
                return HttpNotFound();
            }
            return View(yoneticiler);
        }

        // POST: Yonetim/Edit/5
          [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Yoneticiler yoneticiler)
        {
            ModelState.Remove("KimKayitEtti");
            ModelState.Remove("KayitTarih");
            ModelState.Remove("IsActive");
            if (ModelState.IsValid)
            {
                BusinessLayerResult<Yoneticiler> res = y.Update(yoneticiler);
                if (res.Errors.Count > 0)
                {
                    res.Errors.ForEach(x => ModelState.AddModelError("", x.Message));
                    return View(yoneticiler);
                }
                /* Yoneticiler yo = y.Find(x => x.Id == yoneticiler.Id);
                 yo.Adi = yoneticiler.Adi;
                 yo.Soyadi = yoneticiler.Soyadi;
                 yo.Tc = yoneticiler.Tc;
                 yo.DogumTarih = yoneticiler.DogumTarih;
                 yo.Eposta = yoneticiler.Eposta;
                 yo.IsActive = yoneticiler.IsActive;
                 yo.KullaniciAdi = yoneticiler.KullaniciAdi;
                 yo.Sifre = yoneticiler.Sifre;
                 yo.Adres = yoneticiler.Adres;
                 yo.Telefon = yoneticiler.Telefon;

                 y.Update(yo);//incelenecek*///bu yöntemi kullanmadık çünkü kullanıcı eklediğimiz için aynı isimleri sorguladık.
                return RedirectToAction("Index","Home");
            }
            return View(yoneticiler);
        }

        // GET: Yonetim/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yoneticiler yoneticiler = y.Find(x => x.Id == id.Value);
            if (yoneticiler == null)
            {
                return HttpNotFound();
            }
            return View(yoneticiler);
        }

        // POST: Yonetim/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Yoneticiler yoneticiler = y.Find(x => x.Id == id);
            y.Delete(yoneticiler);
            return RedirectToAction("Index","Home");
        }

       
    }
}

Mvc/OtoGaleri/Views/Yonetim/Create.cshtml
@model OtoGaleri_Entities.Tablolar.Yoneticiler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Create";
}
<title>Yönetici Oluştur</title>
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Create</h2>
        <hr />
    </div>
  
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Yoneticiler</h4>
                <hr />
              @Html.ValidationSummary(false)
                <div class="form-group">
                    @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tc, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DogumTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DogumTarih, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DogumTarih, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
                    </div>
                </div>

              @*  <div class="form-group">
                    @Html.LabelFor(model => model.KayitTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KayitTarih, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KayitTarih, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KimKayitEtti, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KimKayitEtti, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KimKayitEtti, "", new { @class = "text-danger" })
                    </div>
                </div>
                *@
                <div class="form-group">
                    @Html.LabelFor(model => model.KullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KullaniciAdi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.AktiflikGuid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AktiflikGuid, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AktiflikGuid, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit"  class="btn btn-success" >
                            <span class="glyphicon glyphicon-plus"></span>Oluştur
                        </button>
                        @*@Html.ActionLink("Listeye Dön", "Index","Yonetim",null,new { @class = "btn btn-default" })*@
                        <a href="@Html.EncodedLink("", "Index", "Yonetim", new { }, new { @class = "form-control"})" class="btn btn-default">
                           Listeye Dön
                        </a>
                    </div>
                </div>
            </div>
        }

        <div>
           
        </div>



    </div>

</div>

Mvc/OtoGaleri/Views/Yonetim/Delete.cshtml
@model OtoGaleri_Entities.Tablolar.Yoneticiler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Delete";
}
<title>Yönetici Sil</title>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Silinecek</h2>
        <hr />
        <h3>Silmek İstediğine Emin Misin ?</h3>
    </div>

</div>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h4>Yoneticiler</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Adi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Soyadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Soyadi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tc)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Eposta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Eposta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DogumTarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DogumTarih)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Telefon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telefon)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KayitTarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KayitTarih)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KimKayitEtti)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KimKayitEtti)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KullaniciAdi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KullaniciAdi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sifre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sifre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adres)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adres)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AktiflikGuid)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AktiflikGuid)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-remove"></span>Sil
                </button>
                @*@Html.ActionLink("Listeye Dön", "Index", "Yonetim", null, new { @class = "btn btn-default" })*@
                <a href="@Html.EncodedLink("", "Index", "Yonetim", new { id=Model.Id}, new { @class = "form-control"})" class="btn btn-default">
                   Listeye Dön
                </a>
            </div>
        }
    </div>
</div>

Mvc/OtoGaleri/Views/Yonetim/Details.cshtml
@model OtoGaleri_Entities.Tablolar.Yoneticiler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Details";
}
<title>Yönetici Detay</title>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Detaylar</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h4>Yöneticiler</h4>
        <hr />
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <img src="~/Images/@Model.Resim" class="img-circle" width="128" height="128" />
                @Html.HiddenFor(model => model.Resim)
                </div>
            </div>
                
                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.Adi)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Adi)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Soyadi)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Soyadi)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Tc)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Tc)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Eposta)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Eposta)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DogumTarih)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DogumTarih)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Telefon)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Telefon)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.KayitTarih)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.KayitTarih)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.KimKayitEtti)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.KimKayitEtti)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.KullaniciAdi)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.KullaniciAdi)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Sifre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Sifre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Adres)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Adres)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>



                </dl>

                <p>

                    @*<a href="/Yonetim/Edit/@Model.Id" class="btn btn-success">
                        <span class="glyphicon glyphicon-edit"></span>Düzenle
                    </a>*@
                    <a href="@Html.EncodedLink("", "Edit", "Yonetim", new { id=Model.Id}, new { @class = "form-control"})" class="btn btn-success">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    <a href="@Html.EncodedLink("", "Index", "Yonetim", new { id=Model.Id}, new { @class = "form-control"})" class="btn btn-default">
                        <span class="glyphicon glyphicon-arrow-left"></span>Tüm Liste
                    </a>
                    @*<a href="/Yonetim/Index" class="btn btn-default">
                        <span class="glyphicon glyphicon-arrow-left"></span>Tüm Liste
                    </a>*@
                </p>
            </div>
        </div>

Mvc/OtoGaleri/Views/Yonetim/Edit.cshtml
@model OtoGaleri_Entities.Tablolar.Yoneticiler
@using OtoGaleri.RazorHelpers
@{
    ViewBag.Title = "Edit";
}
<title>Yönetici Düzenle</title>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Düzenle</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Yoneticiler</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tc, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DogumTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DogumTarih, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DogumTarih, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.KayitTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KayitTarih, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KayitTarih, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.KimKayitEtti, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KimKayitEtti, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KimKayitEtti, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.KullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KullaniciAdi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.AktiflikGuid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AktiflikGuid, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AktiflikGuid, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-floppy-disk"></span>Kaydet
                    </button>
                    @*@Html.ActionLink("Listeye Dön", "Index", "Yonetim", null, new { @class = "btn btn-default" })*@
                    <a href="@Html.EncodedLink("", "Index", "Yonetim", new {}, new { @class = "form-control"})" class="btn btn-info">
                        Listeye Dön
                    </a>
                </div>
                
            </div>
        }

        
</div>
</div>