Mvc/OtoGaleri/Controllers/ArabalarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using OtoGaleri_Entities.Tablolar;
using OtoGaleri_BusinessLayer;
using OtoGaleri_BusinessLayer.Result;
using OtoGaleri.ViewModels;
using OtoGaleri.Utils;

namespace OtoGaleri.Controllers
{
    public class ArabalarController : CarController
    {
      private ArabalarManager a = new ArabalarManager();
      private YeniArabalarManager yenia = new YeniArabalarManager();
      private  SifirBegenilenArabalarManager begenilenler = new SifirBegenilenArabalarManager();
      private  SifirSatilmayanArabalarManager satilmayanaraba = new SifirSatilmayanArabalarManager();
      private KiralikArabalarManager kiralikmanager = new KiralikArabalarManager();
        private SifirSatilanArabaManager sifirsatilan = new SifirSatilanArabaManager();
        private KullaniciManager kma = new KullaniciManager();
        private KiralikBekleyenManager kiralik_bekleyen = new KiralikBekleyenManager();
        private IkinciElManager ikincielarabalar = new IkinciElManager();
        private KirayaVerilmisArabalarManager kirayaverilmismanager = new KirayaVerilmisArabalarManager();
        private IkinciElSatilmisArabalarManager ikincielsatilmisarabalarmanager = new IkinciElSatilmisArabalarManager();
        private IkinciElSatilmayanArabalarManager ikincielsatilmayanarabamanager = new IkinciElSatilmayanArabalarManager();
        private GelirlerManager gelirmanager = new GelirlerManager();
        private KullaniciManager kullanicimanager = new KullaniciManager();
        private YoneticiManager yöneticiManager = new YoneticiManager();
        
        // GET: Arabalar
        public ActionResult Index()
        {
            


            return View(a.List());
        }
        
     

        // GET: Arabalar/Details/5
        public ActionResult Details(int? id)
        {
          
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Arabalar arabalar = a.Find(x => x.Id == id.Value);
            if (arabalar.Durum == OtoGaleri_Entities.ArabalarEnums.Durum2.IkinciEl)
            {
                IkinciEl ikinciel = ikincielarabalar.Find(x => x.Arabaid.Id == arabalar.Id);
                int a = ikinciel.Km;
                TempData["km"] = a;
            }
                if (arabalar == null)
                {
                    return HttpNotFound();
                }

                return View(arabalar);
          
        }
    
        public ActionResult BegenilenAraba(int? id)
        {
            ModelState.Remove("Araba");
            if (ModelState.IsValid)
            {
                Kullanicilar ku = Session["logink"] as Kullanicilar;
                if (id == null)
                {
                    return View(begenilenler.List(x => x.Kullanici.Id == ku.Id));
                }
                
                SifirBegenilenArabalar ba = new SifirBegenilenArabalar();
                Arabalar aa = a.Find(x => x.Id == id.Value);
             //   KiralikArabalar kk = kiralikmanager.Find(x => x.Id == id.Value);
                if (Session["logink"] != null && aa!=null )
               {
                    //ba = begenilenler.Find(x => x.Araba == aa && x.Kullanici == ku);
                    //if (ba == null)
                    //{
                        ba.Kullanici = ku;
                        ba.Araba = aa;
                        //   ba.begenildimi = 1;//begenildimiyi gerekirse sil biryerde kullanmadım şuanlık....
                        begenilenler.Insert(ba);
                    //}


               }
                
                return View(begenilenler.List(x=>x.Kullanici.Id==ku.Id));


            }
            return View();
        }
        public ActionResult BegenilenArabaDetay(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SifirBegenilenArabalar arabalar = begenilenler.Find(x => x.Id == id.Value);

            if (arabalar == null)
            {
                return HttpNotFound();
            }

            return View(arabalar);
        }
        [HttpPost]
        public ActionResult BegenilenArabaDetay(int id)
        {
            SifirBegenilenArabalar araba = begenilenler.Find(x => x.Id == id);
            begenilenler.Delete(araba);
            return RedirectToAction("BegenilenAraba");

           
        }
        //--Araba sATIŞ VE KİRALAMANIN İşlemlerinin başladığı yer
        public ActionResult PersonelIslem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arabalar arabalar = a.Find(x => x.Id == id.Value);
            TempData["araba"] = arabalar.Id;
            if (arabalar == null)
            {
                return HttpNotFound();
            }

            return View(arabalar);
           
        }
        public ActionResult PesonelIslemKullanicisi()
        {
            return View();

        }

        [HttpPost]
        public ActionResult PesonelIslemKullanicisi(SifirSatilanAraba model)
        {         

                int idsi = Convert.ToInt32(TempData["araba"]);
                YeniArabalar car = yenia.Find(x => x.Arabaid.Id == idsi);
            Yoneticiler y = Session["loginy"] as Yoneticiler;
                Kullanicilar ku = kma.Find(x => x.Tc == model.SatilanKullanici.Tc);
            if (ku == null)
            {
                ErrorViewModel notifyonj = new ErrorViewModel()
                {
                    Title = "Kullanıcı Tc'si hatalı böyle bir kullanıcı bulunamadı..",
                    RedirectingUrl = "/Home/PesonelIslemKullanicisi"
                };
                return View("Error", notifyonj);
            }
            SifirSatilanAraba yenisat = new SifirSatilanAraba();
                yenisat.SifirArabalar = car;
                yenisat.SatilanKullanici = ku;
                yenisat.SatilmaTarih = DateTime.Now;
                yenisat.SatilmaUcret = model.SatilmaUcret;
                yenisat.SatanPersonel = y.Adi+" "+y.Adres;
                sifirsatilan.Insert(yenisat);
                try
                {
                    Arabalar aa = a.Find(x => x.Id == car.Arabaid.Id);
                    aa.IslemYapabilme = false;
                    a.Update(aa);

                    SifirSatilmayanArabalar satilma = satilmayanaraba.Find(x => x.SatilmayanAraba.Id == car.Id);
                    satilmayanaraba.Delete(satilma);
                    car.Durum = OtoGaleri_Entities.IkincielEnums.Durum.Satildi;
                    yenia.Update(car);

                Gelirler gelir = new Gelirler();
                gelir.Araba = aa;
                gelir.ArabaninDurumu = aa.Durum;
                gelir.Kullanici = ku;
                gelir.Tarih = DateTime.Now;
                gelir.Personel = yenisat.SatanPersonel; //sifir satılmış personelden çektik ilerde deişiklik yapabilirim...
                gelir.Fiyat = yenisat.SatilmaUcret;
                gelirmanager.Insert(gelir);

                OkViewModel notifyobj = new OkViewModel()
                    {

                        Title = "Güncelleme Başarılı",
                        RedirectingUrl = "/Home/Index",

                    };
                    notifyobj.Items.Add("Satış işleminiz başarılı bir şekilde gerçekleşmiştir.");
                    return View("Ok", notifyobj);
                }
                catch (Exception)
                {
                    ErrorViewModel notifyonj = new ErrorViewModel()
                    {
                        Title = "Hata Oluştu.",
                    };
                    return View("Error", notifyonj);

                }

           
           
        }
      
        public ActionResult PersonelSifirSatilanArabalar()
        {
            int sifirkazanilan = sifirsatilan.List().Sum(x => x.SatilmaUcret);
            TempData["sifirkazanilan"] = sifirkazanilan;
            return View(sifirsatilan.List());
        }
        public ActionResult PersonelSifirSatilanArabaDetay(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SifirSatilanAraba arabalar = sifirsatilan.Find(x => x.Id == id.Value);

            if (arabalar == null)
            {
                return HttpNotFound();
            }

            return View(arabalar);
        }
        //--Sıfır arabalarının işlemlerinin bittiği yer

        //--Kiralık arabaların işlemlerinin başladığı yer
        public ActionResult PesonelIslemKullanicisikiralik()
        {
            return View();

        }
        [HttpPost]
        public ActionResult PesonelIslemKullanicisikiralik(KirayaVerilmisArabalar model)
        {
            if (model.KiradanAlamaTarih >= DateTime.Today && model.KiralamaTarih>=DateTime.Today)
            {//olmadı yine dene......
                int idsi = Convert.ToInt32(TempData["araba"]);
                KiralikArabalar car = kiralikmanager.Find(x => x.Arabaid.Id == idsi);
                Kullanicilar ku = kma.Find(x => x.Tc == model.HangiKullanici.Tc);
                Ortak123 ortakk = Session["loginy"] as Yoneticiler;
                Ortak123 ortakk1 = Session["loginp"] as Personeller;
                Ortak123 ortakkkisi;
                if (ortakk == null)
                {
                    ortakkkisi = ortakk1;
                }else
                {
                    ortakkkisi = ortakk;
                }
                if (ku == null)
                {
                    ErrorViewModel notifyonj = new ErrorViewModel()
                    {

Mvc/OtoGaleri/Views/Arabalar/BegenilenAraba.cshtml
@using OtoGaleri_Entities.Tablolar
@model IEnumerable<OtoGaleri_Entities.Tablolar.SifirBegenilenArabalar>

    @{
        ViewBag.Title = "GelenAraba";
    }
<title>Beğenilen Arabalar</title>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>Beğenilen Arabalar</h2>
            <hr />
        </div>

    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Marka)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Model)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Yakit)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Cekis)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Garanti)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Aciklama)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Fiyat)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Araba.Durum)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Marka)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Model)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Yakit)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Cekis)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Garanti)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Aciklama)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Fiyat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Araba.Durum)
                        </td>
                        <td>

                            <a href="/Arabalar/BegenilenArabaDetay/@item.Id" class="btn btn-info">
                                <span class="glyphicon glyphicon-search"></span>
                            </a>
                            @if (item.Araba.IslemYapabilme == false)
                            {
                                <a href="#" class="btn btn-danger">
                                    İşlem Yapılamaz
                                </a>
                            }

                        </td>
                    </tr>
                }

            </table>







            </div>
        </div>





  

Mvc/OtoGaleri/Views/Arabalar/BegenilenArabaDetay.cshtml
@model OtoGaleri_Entities.Tablolar.SifirBegenilenArabalar
@{
    ViewBag.Title = "BegenilenArabaDetay";
}
<title>Beğenilen Arabalar Detay</title>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Detaylar</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h4>Araba</h4>
        <hr />

        <img src="~/Images/@Model.Araba.Resim1" class="img-circle" width="128" height="128" />
        @Html.HiddenFor(model => model.Araba.Resim1)
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Araba.Marka)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Araba.Marka)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Araba.Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Araba.Model)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Araba.Kasatipi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Araba.Kasatipi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Araba.Renk)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Araba.Renk)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Araba.Fiyat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Araba.Fiyat)
            </dd>
         
        </dl>
        
           
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                
                <div class="form-actions no-color">
                    <button type="submit" class="btn btn-danger">
                        <span class="glyphicon glyphicon-remove"></span>Sil
                    </button>
                   
                    @Html.ActionLink("Listeye Dön", "BegenilenAraba", "Arabalar", null, new { @class = "btn btn-default" })
                </div>
            }

        
</div>
    </div>

Mvc/OtoGaleri/Views/Arabalar/BosDetails.cshtml
@model OtoGaleri_Entities.Tablolar.Arabalar
@{
    Layout = null;
}

@*<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BosDetails</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>*@
<div class="row">
    <div class="col-md-8 col-md-offset-2">      
        <img src="~/Images/@Model.Resim1" class="img-circle" width="128" height="128" />
        @Html.HiddenFor(model => model.Resim1)

        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.IlanTarihi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IlanTarihi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Marka)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Marka)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Model)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Yil)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Yil)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Yakit)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Yakit)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Vites)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vites)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Garanti)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Garanti)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Kasatipi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kasatipi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MotorGucu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MotorGucu)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MotorHacmi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MotorHacmi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Cekis)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cekis)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Renk)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Renk)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ArabayiEkleyen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ArabayiEkleyen)
            </dd>
            @*bas*@
            @if (Model.Durum == OtoGaleri_Entities.ArabalarEnums.Durum2.IkinciEl)
            {

                <dt>
                    @Html.DisplayName("Km")
                </dt>

                <dd>
                    @TempData["km"]
                </dd>
            }
            @*son*@
            <dt>
                @Html.DisplayNameFor(model => model.Fiyat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fiyat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EklenmeTarihi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EklenmeTarihi)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.Durum)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Durum)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tipi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tipi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Aciklama)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Aciklama, new { @class = "form-control", @rows = 3, disabled = "disabled" })
            </dd>

        </dl>

        <p>
            @if (Session["loginy"] != null || Session["loginp"] != null)
            {
                <a href="/Arabalar/Edit/@Model.Id" class="btn btn-success">
                    <span class="glyphicon glyphicon-edit"></span>Düzenle
                </a>
                <a href="/Arabalar/Index" class="btn btn-default">
                    <span class="glyphicon glyphicon-arrow-left"></span>Tüm Liste
                </a>
            }
            else
            {
                <a href="/Home/Index" class="btn btn-success">
                    <span class="glyphicon glyphicon-home"></span>AnaSayfa
                </a>

            }

        </p>
    </div>
</div>

Mvc/OtoGaleri/Views/Arabalar/KiralikArabaGunUzat.cshtml
@model OtoGaleri_Entities.Tablolar.KirayaVerilmisArabalar
@{
    ViewBag.Title = "KiralikArabaGunUzat";
}
<title>Kiralık Araba Gün Uzat</title>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Kiralık Araba Gün Uzat</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h4>Uzatılacak Araba</h4>
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.HangiKullanici.Adi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HangiKullanici.Adi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HangiKullanici.Soyadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HangiKullanici.Soyadi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HangiKullanici.Tc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HangiKullanici.Tc)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.HangiKullanici.Eposta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HangiKullanici.Eposta)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Marka)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Marka)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Model)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Kasatipi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Kasatipi)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Renk)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Renk)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Vites)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Vites)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Yakit)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Yakit)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralikAraba.Arabaid.Fiyat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralikAraba.Arabaid.Fiyat)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.KiralamaTarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiralamaTarih)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KiradanAlamaTarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KiradanAlamaTarih)
            </dd>
          

           

            </dl>
@using (Html.BeginForm())
{


        <div class="form-group">
            @Html.LabelFor(model => model.KiradanAlamaTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KiradanAlamaTarih, new { htmlAttributes = new { @class = "datapicker form-control" } })
                @Html.ValidationMessageFor(model => model.KiradanAlamaTarih, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>Günü Uzat
                </button>
                @Html.ActionLink("Listeye Dön", "PersonelKiralananArabalar", "Arabalar", null, new { @class = "btn btn-default" })
            </div>

        </div>



}

</div>
    </div>


@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>

        $(function(){
            $(".datapicker").datepicker({

                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                //  yearRange: "2018:2020",
                minDate: new Date(2018, 0, 1),
                maxDate: new Date(2020, 0, 1),
                showOn: "both"


            });

          });
    </script>

}

Mvc/OtoGaleri/Views/Arabalar/PesonelIslemKullanicisikiralik.cshtml
@model OtoGaleri_Entities.Tablolar.KirayaVerilmisArabalar
@{
    ViewBag.Title = "PesonelIslemKullanicisikiralik";
}
<title>Araba İşlem</title>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/validation-summary.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Kiralanacak Araba</h2>
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Arabalar</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.HangiKullanici, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HangiKullanici.Tc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HangiKullanici, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KiralamaTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KiralamaTarih, new { htmlAttributes = new { @class = "datapicker form-control" } })
                        @Html.ValidationMessageFor(model => model.KiralamaTarih, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.KiradanAlamaTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KiradanAlamaTarih, new { htmlAttributes = new { @class = "datapicker form-control" } })
                        @Html.ValidationMessageFor(model => model.KiradanAlamaTarih, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AlinacakUcret, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AlinacakUcret, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AlinacakUcret, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>Oluştur
                        </button>
                        @Html.ActionLink("Listeye Dön", "Index", "Arabalar", null, new { @class = "btn btn-default" })
                    </div>

                </div>
                
     </div>
        }
</div>
 </div>


@section scripts{
    
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>

        $(function(){
            $(".datapicker").datepicker({

                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                //  yearRange: "2018:2020",
                minDate: new Date(2018, 0, 1),
                maxDate: new Date(2020, 0, 1),
                showOn: "both"


            });

          });
    </script>
    
    }